# Redisson-config
singleServerConfig:
#  address: redis://redis-10457.c1.asia-northeast1-1.gce.cloud.redislabs.com:10457
#  password: vMak1lRyRBt7144gTTWTp7uyVF9uUfzg
  address: redis://192.227.160.174:6379
  password: 
  clientName: null
  database: 0
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 4
  connectionPoolSize: 10
  dnsMonitoringInterval: 5000
  #dnsMonitoring: false

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"